$Scale 41

$ModelName "ValeyardStudios\Brackint\Roof.mdl"

$BodyGroup "Roof"
{
    studio "Roof.smd"
}


$CDMaterials "valeyardstudios/brackolin/interior/room"

$SurfaceProp "default"

$Contents "solid"

$CBox 0 0 0 0 0 0

$bbox -39.267 -45.303 -10.767 39.267 45.303 45.835

$sequence "idle" "anims\idle.smd" {
    fps 30
}


$texturegroup skinfamilies
{
    {"RoofLights"}
    {"RoofLights_Off"}
    {"RoofLights_Warn"}
}