$Scale 41

$ModelName "ValeyardStudios\Brackint\RoundelSet1.mdl"

$BodyGroup "RoundelSet1"
{
    studio "RoundelSet1.smd"
}

$CDMaterials "valeyardstudios/brackolin/interior/roundels"

$SurfaceProp "wood"

$Contents "solid"

$CBox 0 0 0 0 0 0

$bbox -39.267 -45.303 -10.767 39.267 45.303 45.835

$sequence "idle" "anims\idle.smd" {
    fps 30
}

$texturegroup skinfamilies
{
    {"Roundel"}
    {"Roundel_R"}
    {"Roundel_G"}
    {"Roundel_B"}
    {"Roundel_U"}
}