local E = {
    ID = "brackolin_ext",
    Base = "base",
    Name = "Brackolin (1966+1996)",
    Category = "ValeyardStudios",
		Model="models/valeyardstudios/brackolin/brackolinshell.mdl",
		Mass=2900,
		ScannerOffset=Vector(30,0,50),
Portal = {
	-- Generated by portals debug tool
	pos = Vector(27.778673171997, 0, 47.134754180908),
	ang = Angle(4.1688172358612e-10, 0, 0),
	width = 45,
	height = 82.859959776993,
	thickness = 22,
	inverted = true,
},


	Fallback={
		pos=Vector(55,0,5),
		ang=Angle(0,0,0)
	},
	Light={
		enabled=true,
		pos=Vector(0, 0, 110),
		color=Color(155,155,155)
	},
	Sounds={
		Teleport={
			demat="flight/demat.wav",
			mat="flight/mat.wav",
		},
		FlightLoop="flight/interior_flight.wav"
	},

Parts={
	vortex = {
			model = "models/valeyardstudios/vortex/vortex.mdl",
		},
	door={
		model="models/valeyardstudios/brackolin/brackolindoors.mdl",
		posoffset=Vector(-27.778673171997, 0, -47.134754180908),
		angoffset = Angle(0,0,0)
	}
},
Teleport={
		SequenceSpeed=0.75,
		SequenceSpeedFast=1,
		DematSequenceDelays={
			[2] = 1
			},
		DematSequence={
			150,
			250,
			100,
			150,
			75,
			100,
			50,
			75,
			0
		},
		MatSequence={
			75,
			50,
			100,
			75,
			150,
			100,
			250,
			150,
			255
		    }
      }
    }

 

TARDIS:AddExterior(E)